"use client";

import { useMemo, useState } from "react";

type Player={id:string;name:string;number:number;role:string;groupName:string;bio:string;photoKey:string|null;active:number};
type Event={id:string;type:string;title:string;startsAt:string;location:string;opponent:string;notes:string;published:number};
type Attendance={id:string;eventId:string;playerId:string;status:string;note:string};
type Vote={id:string;playerNumber:number;rating:number;eventId:string|null;fanName:string;message:string;status:string;createdAt:string;playerName:string|null};
type Message={id:string;playerNumber:number|null;senderName:string;body:string;status:string;createdAt:string;playerName:string|null};
type Sponsor={id:string;name:string;website:string;logoKey:string|null;active:number;sortOrder:number};
type Match={id:string;round:number;phase:string;home:string;away:string;scheduledAt:string;sourceDate:string;time:string;field:string;homeGoals:number|null;awayGoals:number|null;status:string;sourceAnomaly:number};
type Standing={team:string;played:number;wins:number;draws:number;losses:number;goalsFor:number;goalsAgainst:number;goalDifference:number;points:number};
type Snapshot={players:Player[];events:Event[];attendance:Attendance[];votes:Vote[];messages:Message[];sponsors:Sponsor[];settings:Record<string,string>;matches:Match[];standings:Standing[]};

type Tab="overview"|"players"|"events"|"league"|"votes"|"messages"|"content";
const NAC="NAC AMATORI CASTELLANA";
const groups=["Portieri","Difensori","Centrocampisti","Attaccanti"];

export default function AdminDashboard({initialData,userName,signOutPath}:{initialData:Snapshot;userName:string;signOutPath:string}){
  const [data,setData]=useState(initialData);const [tab,setTab]=useState<Tab>("overview");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
  const mutate=async(action:string,payload:Record<string,unknown>={})=>{setBusy(true);setNotice("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Operazione non riuscita");setData(j);setNotice("Salvato");}catch(e){setNotice(e instanceof Error?e.message:"Errore");}finally{setBusy(false)}};
  const refresh=async()=>{const r=await fetch("/api/admin",{cache:"no-store"});if(r.ok)setData(await r.json())};
  const upload=async(entity:"player"|"sponsor",id:string,file:File)=>{setBusy(true);const f=new FormData();f.set("entity",entity);f.set("id",id);f.set("file",file);try{const r=await fetch("/api/admin/upload",{method:"POST",body:f});const j=await r.json();if(!r.ok)throw new Error(j.error||"Upload non riuscito");await refresh();setNotice("Immagine caricata");}catch(e){setNotice(e instanceof Error?e.message:"Errore upload");}finally{setBusy(false)}};
  const pendingVotes=data.votes.filter(v=>v.status==="pending").length,pendingMessages=data.messages.filter(m=>m.status==="pending").length;
  return <main className="adm"><aside className="adm-side"><a href="/" className="adm-brand">NAC <span>CONTROL ROOM</span></a><div className="adm-user">{userName}</div>{([['overview','Panoramica'],['players','Rosa'],['events','Agenda'],['league','Campionato'],['votes',`Voti${pendingVotes?` (${pendingVotes})`:''}`],['messages',`Messaggi${pendingMessages?` (${pendingMessages})`:''}`],['content','Contenuti']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}<a className="adm-link" href="/" target="_blank">Apri sito pubblico</a><a className="adm-link" href={signOutPath}>Esci</a></aside><section className="adm-main"><header><div><small>STAGIONE 2026/27</small><h1>Gestione NAC</h1></div><span className="adm-notice">{busy?"Salvataggio…":notice}</span></header>{tab==="overview"&&<Overview data={data}/>} {tab==="players"&&<Players data={data} busy={busy} mutate={mutate} upload={upload}/>} {tab==="events"&&<Events data={data} mutate={mutate}/>} {tab==="league"&&<League data={data} busy={busy} mutate={mutate}/>} {tab==="votes"&&<Moderation title="Voti tifosi" items={data.votes} kind="vote" mutate={mutate}/>} {tab==="messages"&&<Moderation title="Messaggi" items={data.messages} kind="message" mutate={mutate}/>} {tab==="content"&&<Content data={data} mutate={mutate}/>}</section></main>;
}

function Overview({data}:{data:Snapshot}){const next=[...data.matches].filter(m=>m.status!=="played"&&new Date(m.scheduledAt)>=new Date()).find(m=>m.home===NAC||m.away===NAC);return <section><div className="adm-head"><small>OGGI</small><h2>Il colpo d’occhio</h2></div><div className="adm-kpis"><Kpi n={data.players.filter(p=>p.active).length} t="Giocatori attivi"/><Kpi n={data.events.length} t="Appuntamenti"/><Kpi n={data.votes.filter(v=>v.status==="pending").length} t="Voti da controllare"/><Kpi n={data.messages.filter(m=>m.status==="pending").length} t="Messaggi nuovi"/></div>{next&&<article className="adm-card"><small>PROSSIMA NAC</small><h3>{next.home} – {next.away}</h3><p>{new Date(next.scheduledAt).toLocaleDateString("it-IT")} · {next.time}<br/>{next.field}</p></article>}</section>}
function Kpi({n,t}:{n:number|string;t:string}){return <article className="adm-kpi"><b>{n}</b><span>{t}</span></article>}

function Players({data,busy,mutate,upload}:{data:Snapshot;busy:boolean;mutate:(a:string,p?:Record<string,unknown>)=>void;upload:(e:"player"|"sponsor",id:string,f:File)=>void}){const [newP,setNewP]=useState({name:"",role:"",groupName:"Difensori",bio:""});const used=new Set(data.players.map(p=>p.number));const internalNumber=Array.from({length:99},(_,i)=>i+1).find(n=>!used.has(n))||99;return <section><div className="adm-head"><small>ROSA</small><h2>Giocatori</h2></div><form className="adm-form-row" onSubmit={e=>{e.preventDefault();mutate("player.create",{...newP,number:internalNumber});setNewP({name:"",role:"",groupName:"Difensori",bio:""})}}><input required placeholder="Nome e cognome" value={newP.name} onChange={e=>setNewP({...newP,name:e.target.value})}/><input required placeholder="Ruolo" value={newP.role} onChange={e=>setNewP({...newP,role:e.target.value})}/><select value={newP.groupName} onChange={e=>setNewP({...newP,groupName:e.target.value})}>{groups.map(g=><option key={g}>{g}</option>)}</select><button disabled={busy}>Aggiungi</button></form><div className="adm-list">{data.players.map(p=><PlayerRow key={p.id} p={p} busy={busy} mutate={mutate} upload={upload}/>)}</div></section>}
function PlayerRow({p,busy,mutate,upload}:{p:Player;busy:boolean;mutate:(a:string,p?:Record<string,unknown>)=>void;upload:(e:"player"|"sponsor",id:string,f:File)=>void}){const [f,setF]=useState(p);return <article className={`adm-row ${p.active?"":"muted"}`}><div className="adm-fields"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input value={f.role} onChange={e=>setF({...f,role:e.target.value})}/><select value={f.groupName} onChange={e=>setF({...f,groupName:e.target.value})}>{groups.map(g=><option key={g}>{g}</option>)}</select><textarea placeholder="Bio" value={f.bio} onChange={e=>setF({...f,bio:e.target.value})}/></div><div className="adm-actions"><label className="file-btn">Foto<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload("player",p.id,e.target.files[0])}/></label><button disabled={busy} onClick={()=>mutate("player.update",f)}>Salva</button><button className="ghost" onClick={()=>mutate("player.toggle",{id:p.id,active:!p.active})}>{p.active?"Nascondi":"Riattiva"}</button></div></article>}

function Events({data,mutate}:{data:Snapshot;mutate:(a:string,p?:Record<string,unknown>)=>void}){const [f,setF]=useState({type:"allenamento",title:"Allenamento",startsAt:"",location:"Castellana",opponent:"",notes:"",published:true});return <section><div className="adm-head"><small>AGENDA</small><h2>Appuntamenti</h2></div><form className="adm-form-grid" onSubmit={e=>{e.preventDefault();mutate("event.create",f);setF({...f,startsAt:"",opponent:"",notes:""})}}><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>allenamento</option><option>partita</option><option>amichevole</option><option>torneo</option></select><input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input required type="datetime-local" value={f.startsAt} onChange={e=>setF({...f,startsAt:e.target.value})}/><input placeholder="Luogo" value={f.location} onChange={e=>setF({...f,location:e.target.value})}/><input placeholder="Avversario" value={f.opponent} onChange={e=>setF({...f,opponent:e.target.value})}/><button>Aggiungi</button></form><div className="adm-list">{data.events.map(e=><article className="adm-card" key={e.id}><small>{e.type.toUpperCase()}</small><h3>{e.title}</h3><p>{new Date(e.startsAt).toLocaleString("it-IT")} · {e.location}{e.opponent?` · ${e.opponent}`:""}</p><button className="danger" onClick={()=>mutate("event.delete",{id:e.id})}>Elimina</button></article>)}</div></section>}

function League({data,busy,mutate}:{data:Snapshot;busy:boolean;mutate:(a:string,p?:Record<string,unknown>)=>void}){const [onlyNac,setOnlyNac]=useState(true);const matches=onlyNac?data.matches.filter(m=>m.home===NAC||m.away===NAC):data.matches;return <section><div className="adm-head"><small>CAMPIONATO</small><h2>Risultati e classifica</h2></div><div className="adm-toggle"><button className={onlyNac?"active":""} onClick={()=>setOnlyNac(true)}>Solo NAC</button><button className={!onlyNac?"active":""} onClick={()=>setOnlyNac(false)}>Tutto il girone</button></div><div className="adm-match-list">{matches.map(m=><MatchRow key={m.id} m={m} busy={busy} mutate={mutate}/>)}</div><div className="adm-table-wrap"><table><thead><tr><th>#</th><th>Squadra</th><th>PG</th><th>V</th><th>N</th><th>P</th><th>DR</th><th>PT</th></tr></thead><tbody>{data.standings.map((r,i)=><tr key={r.team} className={r.team===NAC?"nac":""}><td>{i+1}</td><td>{r.team}</td><td>{r.played}</td><td>{r.wins}</td><td>{r.draws}</td><td>{r.losses}</td><td>{r.goalDifference}</td><td><b>{r.points}</b></td></tr>)}</tbody></table></div></section>}
function MatchRow({m,busy,mutate}:{m:Match;busy:boolean;mutate:(a:string,p?:Record<string,unknown>)=>void}){const [hg,setHg]=useState(m.homeGoals==null?"":String(m.homeGoals)),[ag,setAg]=useState(m.awayGoals==null?"":String(m.awayGoals));return <article className={`adm-match ${m.home===NAC||m.away===NAC?"nac":""}`}><div><small>{m.phase.toUpperCase()} · {m.round}ª · {new Date(m.scheduledAt).toLocaleDateString("it-IT")} · {m.time}</small><h3>{m.home} <span>vs</span> {m.away}</h3><p>{m.field}</p></div><div className="score"><input type="number" min="0" value={hg} onChange={e=>setHg(e.target.value)}/><span>–</span><input type="number" min="0" value={ag} onChange={e=>setAg(e.target.value)}/><button disabled={busy||hg===""||ag===""} onClick={()=>mutate("match.result",{id:m.id,homeGoals:Number(hg),awayGoals:Number(ag)})}>Salva</button><button className="ghost" onClick={()=>mutate("match.status",{id:m.id,status:m.status==="postponed"?"scheduled":"postponed"})}>{m.status==="postponed"?"Ripristina":"Rinvia"}</button></div></article>}

function Moderation({title,items,kind,mutate}:{title:string;items:(Vote|Message)[];kind:"vote"|"message";mutate:(a:string,p?:Record<string,unknown>)=>void}){return <section><div className="adm-head"><small>MODERAZIONE</small><h2>{title}</h2></div><div className="adm-list">{items.length===0&&<p>Nessun elemento.</p>}{items.map(i=><article className="adm-card" key={i.id}><small>{new Date(i.createdAt).toLocaleString("it-IT")} · {i.status}</small><h3>{i.playerName||"Giocatore NAC"}</h3><p><b>{"fanName" in i?i.fanName:i.senderName}</b> — {"message" in i?i.message:i.body}</p>{"rating" in i&&<p className="stars">{"★".repeat(i.rating)}{"☆".repeat(5-i.rating)}</p>}<div className="adm-actions"><button onClick={()=>mutate(`${kind}.status`,{id:i.id,status:"approved"})}>Approva</button><button className="ghost" onClick={()=>mutate(`${kind}.status`,{id:i.id,status:"archived"})}>Archivia</button><button className="danger" onClick={()=>mutate(`${kind}.delete`,{id:i.id})}>Elimina</button></div></article>)}</div></section>}

function Content({data,mutate}:{data:Snapshot;mutate:(a:string,p?:Record<string,unknown>)=>void}){const [f,setF]=useState({hero_title:data.settings.hero_title||"La squadra.|La città.|La nostra voce.",hero_text:data.settings.hero_text||"Passione, unione e rispetto.",history_title:data.settings.history_title||"Amatori,|ma sul serio.",history_text:data.settings.history_text||"",partner_text:data.settings.partner_text||"",instagram:data.settings.instagram||"",facebook:data.settings.facebook||"",whatsapp:data.settings.whatsapp||""});return <section><div className="adm-head"><small>SITO</small><h2>Contenuti pubblici</h2></div><form className="adm-content" onSubmit={e=>{e.preventDefault();mutate("settings.setMany",{settings:f})}}><label>Titolo Home<input value={f.hero_title} onChange={e=>setF({...f,hero_title:e.target.value})}/></label><label>Testo Home<textarea value={f.hero_text} onChange={e=>setF({...f,hero_text:e.target.value})}/></label><label>Titolo storia<input value={f.history_title} onChange={e=>setF({...f,history_title:e.target.value})}/></label><label>Testo storia<textarea value={f.history_text} onChange={e=>setF({...f,history_text:e.target.value})}/></label><label>Testo partner<textarea value={f.partner_text} onChange={e=>setF({...f,partner_text:e.target.value})}/></label><input placeholder="Instagram URL" value={f.instagram} onChange={e=>setF({...f,instagram:e.target.value})}/><input placeholder="Facebook URL" value={f.facebook} onChange={e=>setF({...f,facebook:e.target.value})}/><input placeholder="WhatsApp URL" value={f.whatsapp} onChange={e=>setF({...f,whatsapp:e.target.value})}/><button>Salva contenuti</button></form></section>}
